version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: nextjs-primsa-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superblog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: nextjs-primsa-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/superblog_db?schema=public
    env_file:
      - .env

volumes:
  postgres_data:
